### ISSUE TITLE
Implement flush() BufferedWriter in HttpRequestRecordWriterFileTarget

### ISSUE THREAD

**Issue by shibaevv** [vy/hrrs#2]
Will it be possible to add flush() method in HttpRequestRecordWriterTarget interface,
as you are using BufferedWriter in HttpRequestRecordWriterFileTarget class and I could not easily control it flushing strategy.
 
Another option will be – flush writer on enabled changed from true to false (simpler).

package com.vlkan.hrrs.api;
import java.io.Closeable;
public interface HttpRequestRecordWriterTarget<T> extends Closeable {
…
    void flush();
…
}

public class HttpRequestRecordWriterFileTarget implements HttpRequestRecordWriterTarget<String> {
…
    @Override
    public void flush() throws IOException {
        LOGGER.trace("flushing");
        writer.flush();
    }
…
}

**Comment by vy** [comment]
Does 53da6b2 commit fix your problem?

**Comment by shibaevv** [comment]
Thank you, flush is working.
