### ISSUE TITLE
HRRS filter does not save request Form Data

### ISSUE THREAD

**Issue by shibaevv** [vy/hrrs#4]
HRRS filter does not save request Form Data,
eg login form Content-Type: application/x-www-form-urlencoded
form data not found in serialised text
username:myname
password:mypassword
submit:Login

**Comment by vy** [comment]
@shibaevv, oops! A show-stopper bug. Let me look into it. Thanks for the report.

**Comment by vy** [comment]
@shibaevv, it turned out to be a really difficult to solve issue. I needed to do some nasty hacks. I will document them later in the README before a release. Does 01f4b10 commit fix your problem?

**Comment by shibaevv** [comment]
Form data fix (temporary according to Volkan) implemented and confirmed working.

**Comment by vy** [comment]
I am tired of trying to deal with Tomcat gotchas (see [the mailing-list discussion](http://mail-archives.apache.org/mod_mbox/tomcat-users/201709.mbox/%3CCAP7pH7vp6ST1x7ngCWxGPJ8ecbVzxxkyZpgY1ufDSWrYD%2BSHtg%40mail.gmail.com%3E) for details), hence falling back to the old crude fix, which at least works.
