### ISSUE TITLE
Rolling recording file

### ISSUE THREAD

**Issue by shibaevv** [vy/hrrs#5]
We want to record constantly, eg for 1-7 days.
In class com.vlkan.hrrs.servlet.base64.Base64HrrsFilter constructor is using fixed writerTargetFile, which can grow large.
Will be nice to have writerTargetFile rolling, similar to log4j:
log4j.appender.LOGFILE=org.apache.log4j.RollingFileAppender
log4j.appender.LOGFILE.File=hrrs.txt
log4j.appender.LOGFILE.MaxFileSize=10MB
log4j.appender.LOGFILE.MaxBackupIndex=20

**Comment by vy** [comment]
Hey @shibaevv! That was indeed the reason I kept `*Writer` and `*WriterTarget` classes separate. Let me see if I can spare some time to work on this.

**Comment by vy** [comment]
@shibaevv, if you take a quick look at the contents of the `org.apache.logging.log4j.core.appender.rolling` package, you will notice how complicated file rotation might get. You need a rotation trigger and strategy with all the bells and whistles. You can't just blindly check `prevFileName.equals(fileNamePattern.apply(System.currentTimeMillis()))` and commence a rotation. I welcome any well-engineered patches (not just a fix to save the day), but I am really short of time to implement such a relatively big feature myself. I had mentioned about `logrotate` in README. Didn't it work for you?

**Comment by shibaevv** [comment]
Hi Volkan,

I think this simple solution will work..

**Comment by shibaevv** [comment]
I think this simple solution will work..
[Base64HrrsFilter.java.zip](https://github.com/vy/hrrs/files/1517259/Base64HrrsFilter.java.zip)

**Comment by vy** [comment]
Thanks for sharing your solution @shibaevv, but it has two major drawbacks:
1. `Filter` should not deal with file rotation. It is a responsibility of `Writer` and `WriterTarget` classes. (For instance, in Log4j, do you specify/trigger rotation every time you call `log.info(...)`?)
2. Calling `File#length()` for every record is [IMHO] unacceptable from performance PoV.

**Comment by shibaevv** [comment]
It was quick temp solution to fix my problem.
I notice you have @see com.vlkan.hrrs.servlet.HrrsFilter#getMaxRecordablePayloadByteCount(), so you can integrate this rolling functionality on overflow event:
if (recordedLenght > getMaxRecordablePayloadByteCount())

**Comment by vy** [comment]
@shibaevv, I have just released a new library: [rotating-fos](/vy/rotating-fos). I will be using this to enhance `HttpRequestRecordWriterFileTarget`. If you want to give it a try yourself first, go ahead.

**Comment by vy** [comment]
@shibaevv, I have pushed the change and I am about to cut a new release. Please do let me know if it doesn't work for you. (Feel free to re-open the issue.)
